package Analizador.CHTML;

import java_cup.runtime.Symbol;
import EstructurasDatos.NodoArbol;
import EstructurasDatos.NodoError;
import java.util.ArrayList;
//parser chtml

parser code
{:
    public String archivo="null";
    public static ArrayList<NodoError> sitactico= new ArrayList<NodoError>();
    public void agregarerror(int linea,int columna,String tipo,String men)
    {
       NodoError er= new NodoError(linea, columna, tipo, men,archivo);
       sitactico.add(er);
    }
    public static String errorSin="";
    public void syntax_error(Symbol s){
         agregarerror(s.left,s.right,"sintacitico",s.value.toString());
         errorSin=errorSin+"Error en la Línea " + (s.right+1) +" Columna "+s.left+ ". Identificador "+s.value + " no reconocido."+"\n";
         System.err.println("Error de Sintaxis---a");
         System.err.println(s.value.toString());
         System.err.println( "Linea " + s.left );
         System.err.println( "Columna " + s.right );
         
    }
    public  ArrayList<NodoError> Sin()
    {
        return sitactico;
    }
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
         agregarerror(s.left,s.right,"sintacitico",s.value.toString());   
         System.err.println("Error de Sintaxis----b");
         System.err.println(s.value.toString());
         System.err.println( "Linea " + s.left );
         System.err.println( "Columna " + s.right );
    }

:}
action code
{:
    // acciones que podemos hacer en le codigo
    NodoArbol raiz,izq,der,nodo;
    private NodoArbol CrearHoja(String produccion,String valor,int linea,int colum)
    {
        NodoArbol nodo= new NodoArbol(produccion,valor,linea,colum);
        return nodo;
    }
    private NodoArbol AddHijo(NodoArbol raiz,NodoArbol hijo){
            raiz.add(hijo);
            return raiz;
     }

:}

terminal String CHTML,FINCHTML,ENCABEZADO,FINENCABEZADO,CJS,FINCJS,CCSS,FINCCSS,         
TITULO,FINTITULO,CUERPO,FINCUERPO,PANEL,FINPANEL,IMAGEN,FINIMAGEN,BOTON,FINBOTON,        
ENLACE,FINENLACE;

terminal String TEXTO,FINTEXTO,CAJATEXTO,FINCAJATEXTO,TEXTOA,FINTEXTOA;

terminal String TABLA,FINTABLA,FILT,FINFILT,CB,FINCB,CT,FINCT;

terminal String CAJA,FINCAJA,OPCION,FINOPCION,VALOR,SPINNER, 
FINSPINNER,SALTOFIN,CLICK,RUTA;

terminal String ID,GRUPO,ALTO,ANCHO,ALINEADO,ABRIR,CERRAR,           
PUNTOCOMA,IGUAL,ECADENA,ETEXTO;

nonterminal String inicio;
nonterminal String encabezado,lcompencabezado,compencabezado;
nonterminal String titulo,ccss,cjs;
nonterminal String cuerpo,lcompcuerpo,compcuerpo;       

nonterminal String ruta,click;

nonterminal String  lopciones , opciones, id, grupo, ancho , alto ,alineado;

nonterminal String panel,texto,imagen,boton,enlace;

nonterminal String tabla,celdas,celda,lct,ct,cuerpotabla;

nonterminal String textoa,cajatexto;

nonterminal String caja,lopcion,opcion,valor;

nonterminal  String spinner,saltofin;


start with inicio;

inicio  ::= ABRIR CHTML CERRAR encabezado cuerpo ABRIR FINCHTML CERRAR;

encabezado ::= ABRIR ENCABEZADO CERRAR lcompencabezado ABRIR FINENCABEZADO CERRAR
            |ABRIR ENCABEZADO CERRAR ABRIR FINENCABEZADO CERRAR;

lcompencabezado ::= lcompencabezado compencabezado
                | compencabezado;

compencabezado  ::= titulo
                |ccss
                |cjs;

titulo     ::= ABRIR TITULO CERRAR ETEXTO ABRIR FINTITULO CERRAR;

ccss       ::= ABRIR CCSS RUTA IGUAL ECADENA PUNTOCOMA CERRAR ABRIR FINCCSS CERRAR
           | ABRIR CCSS CERRAR ECADENA ABRIR FINCCSS CERRAR;

cjs        ::= ABRIR CJS RUTA IGUAL ECADENA PUNTOCOMA CERRAR  ABRIR FINCJS CERRAR
           | ABRIR CJS CERRAR ECADENA ABRIR FINCJS CERRAR;


cuerpo     ::= ABRIR CUERPO CERRAR lcompcuerpo ABRIR FINCUERPO CERRAR
           |ABRIR CUERPO CERRAR  ABRIR FINCUERPO CERRAR;

lcompcuerpo ::= lcompcuerpo compcuerpo
            | compcuerpo;  

compcuerpo  ::= panel
            |texto
            |imagen
            |boton
            |enlace
            |tabla
            |textoa
            |cajatexto
            |caja
            |spinner
            |saltofin;


panel       ::= ABRIR PANEL lopciones CERRAR lcompcuerpo ABRIR FINPANEL CERRAR
            | ABRIR PANEL CERRAR lcompcuerpo ABRIR FINPANEL CERRAR
            | ABRIR PANEL lopciones CERRAR  ABRIR FINPANEL CERRAR
            | ABRIR PANEL CERRAR ABRIR FINPANEL CERRAR;

texto       ::= ABRIR TEXTO lopciones CERRAR ETEXTO ABRIR FINTEXTO CERRAR
            |ABRIR TEXTO CERRAR ETEXTO ABRIR FINTEXTO CERRAR
            |ABRIR TEXTO lopciones CERRAR  ABRIR FINTEXTO CERRAR
            |ABRIR TEXTO CERRAR  ABRIR FINTEXTO CERRAR;

imagen      ::= ABRIR IMAGEN CERRAR ECADENA ABRIR FINIMAGEN CERRAR
            |ABRIR IMAGEN lopciones CERRAR ECADENA ABRIR FINIMAGEN CERRAR
            |ABRIR IMAGEN CERRAR  ABRIR FINIMAGEN CERRAR
            |ABRIR IMAGEN lopciones CERRAR  ABRIR FINIMAGEN CERRAR;   

boton       ::= ABRIR BOTON lopciones CERRAR ETEXTO ABRIR FINBOTON CERRAR
            | ABRIR BOTON CERRAR ETEXTO ABRIR FINBOTON CERRAR
            | ABRIR BOTON CERRAR ABRIR FINBOTON CERRAR
            | ABRIR BOTON lopciones CERRAR ABRIR FINBOTON CERRAR;

enlace      ::= ABRIR ENLACE lopciones CERRAR ETEXTO ABRIR FINENLACE CERRAR
            |ABRIR ENLACE CERRAR ETEXTO ABRIR FINENLACE CERRAR
            |ABRIR ENLACE CERRAR  ABRIR FINENLACE CERRAR
            |ABRIR ENLACE lopciones CERRAR ABRIR FINENLACE CERRAR;

tabla       ::= ABRIR TABLA lopciones CERRAR celdas ABRIR FINTABLA CERRAR
            |ABRIR TABLA CERRAR celdas ABRIR FINTABLA CERRAR;

celdas  ::= celdas celda
        | celda;   

celda ::= ABRIR FILT CERRAR lct ABRIR FINFILT CERRAR;

lct ::= lct ct
    |ct;

ct ::= ABRIR CT CERRAR cuerpotabla ABRIR FINCT CERRAR
   | ABRIR CT CERRAR  ABRIR FINCT CERRAR
   |ABRIR CB CERRAR cuerpotabla ABRIR FINCB CERRAR
   | ABRIR CB CERRAR ABRIR FINCB CERRAR;


cuerpotabla ::= texto
            |textoa
            |cajatexto
            |imagen
            |boton;

textoa ::= ABRIR TEXTOA lopciones CERRAR ETEXTO ABRIR FINTEXTOA CERRAR
       |ABRIR TEXTOA CERRAR ETEXTO ABRIR FINTEXTOA CERRAR
       |ABRIR TEXTOA lopciones CERRAR  ABRIR FINTEXTOA CERRAR
       |ABRIR TEXTOA CERRAR  ABRIR FINTEXTOA CERRAR;

cajatexto ::= ABRIR CAJATEXTO lopciones CERRAR ETEXTO ABRIR FINCAJATEXTO CERRAR
       |ABRIR CAJATEXTO CERRAR ETEXTO ABRIR FINCAJATEXTO CERRAR
       |ABRIR CAJATEXTO lopciones CERRAR  ABRIR FINCAJATEXTO CERRAR
       |ABRIR CAJATEXTO CERRAR  ABRIR FINCAJATEXTO CERRAR;

caja ::= ABRIR CAJA lopciones CERRAR lopcion ABRIR FINCAJA CERRAR
     | ABRIR CAJA CERRAR lopcion ABRIR FINCAJA CERRAR
     | ABRIR CAJA lopciones  CERRAR  ABRIR FINCAJA CERRAR
     | ABRIR CAJA  CERRAR  ABRIR FINCAJA CERRAR;

lopcion ::= lopcion opcion
        |opcion;

opcion  ::= ABRIR OPCION valor CERRAR ETEXTO ABRIR FINOPCION CERRAR;

valor  ::= VALOR IGUAL ECADENA;

spinner ::= ABRIR SPINNER lopciones CERRAR ETEXTO ABRIR FINSPINNER CERRAR
        | ABRIR SPINNER CERRAR ETEXTO ABRIR FINSPINNER CERRAR
        | ABRIR SPINNER lopciones CERRAR  ABRIR FINSPINNER CERRAR
        | ABRIR SPINNER  CERRAR  ABRIR FINSPINNER CERRAR;

saltofin ::= ABRIR SALTOFIN lopciones CERRAR 
         |ABRIR SALTOFIN CERRAR;

ruta        ::= RUTA IGUAL ECADENA PUNTOCOMA;

click       ::= CLICK IGUAL ECADENA PUNTOCOMA;

lopciones   ::= lopciones opciones
            |opciones;

opciones    ::= id
            |grupo
            |ancho
            |alto
            |alineado
            |click
            |ruta;
            

id          ::= ID IGUAL ECADENA PUNTOCOMA;
grupo       ::= GRUPO IGUAL ECADENA PUNTOCOMA;
alto        ::= ALTO IGUAL ECADENA PUNTOCOMA;
ancho       ::= ANCHO IGUAL ECADENA PUNTOCOMA;
alineado    ::= ALINEADO IGUAL ECADENA PUNTOCOMA;