
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 13 18:13:48 CST 2018
//----------------------------------------------------

package Analizador.CHTML;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINCT = 35;
  public static final int FINCAJATEXTO = 25;
  public static final int BOTON = 18;
  public static final int FINOPCION = 39;
  public static final int FINENLACE = 21;
  public static final int FINFILT = 31;
  public static final int FINTITULO = 11;
  public static final int ABRIR = 51;
  public static final int SPINNER = 41;
  public static final int FINTEXTOA = 27;
  public static final int ANCHO = 49;
  public static final int CAJA = 36;
  public static final int CUERPO = 12;
  public static final int PUNTOCOMA = 53;
  public static final int FINCB = 33;
  public static final int CJS = 6;
  public static final int CAJATEXTO = 24;
  public static final int CT = 34;
  public static final int FINCCSS = 9;
  public static final int IGUAL = 54;
  public static final int ENLACE = 20;
  public static final int OPCION = 38;
  public static final int FINPANEL = 15;
  public static final int FINCJS = 7;
  public static final int ALINEADO = 50;
  public static final int TITULO = 10;
  public static final int TEXTOA = 26;
  public static final int CB = 32;
  public static final int PANEL = 14;
  public static final int GRUPO = 47;
  public static final int FINIMAGEN = 17;
  public static final int ID = 46;
  public static final int ETEXTO = 56;
  public static final int FINTABLA = 29;
  public static final int EOF = 0;
  public static final int FINCHTML = 3;
  public static final int error = 1;
  public static final int ENCABEZADO = 4;
  public static final int TABLA = 28;
  public static final int CHTML = 2;
  public static final int SALTOFIN = 43;
  public static final int FILT = 30;
  public static final int FINCAJA = 37;
  public static final int ALTO = 48;
  public static final int VALOR = 40;
  public static final int RUTA = 45;
  public static final int IMAGEN = 16;
  public static final int ECADENA = 55;
  public static final int CLICK = 44;
  public static final int CERRAR = 52;
  public static final int CCSS = 8;
  public static final int FINTEXTO = 23;
  public static final int FINSPINNER = 42;
  public static final int TEXTO = 22;
  public static final int FINCUERPO = 13;
  public static final int FINBOTON = 19;
  public static final int FINENCABEZADO = 5;
}

