/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

/**
 *
 * @author Hugo
 */
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import EstructurasDatos.NodoError;

public class PanelErrores extends javax.swing.JPanel {

    /**
     * Creates new form Errores
     */
    private DefaultTableModel modelo;
    public ArrayList<NodoError> errores;
    public PanelErrores() {
        initComponents();
    }
    public PanelErrores(ArrayList errores) {
        initComponents();
        this.errores=errores;
       
        mostrarErrores();
    }
    public void  mostrarErrores()
    {
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"linea","columna","tipo",
            "mensaje","archivo"});
        Object [] filas;
        this.tableError.setModel(modelo);
        
        for (NodoError errore : errores) {
            filas = new Object[]{String.valueOf(errore.getLinea()),
                String.valueOf(errore.getColumna()),errore.getTipo(),errore.getMensaje(),
                errore.getArchivo()
            };
            modelo.addRow(filas);
            
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableError = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Errores"));
        setLayout(new java.awt.BorderLayout());

        tableError.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tableError.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableError);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableError;
    // End of variables declaration//GEN-END:variables
}
