/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.util.ArrayList;
import EstructurasDatos.NodoError;
/**
 *
 * @author Hugo
 */
public class PanelCodigo extends javax.swing.JPanel {

    /**
     * Creates new form PanelCodigo
     */
    private PanelErrores errores;
    public PanelTextos texto;
    public ArrayList <NodoError> listaErroes;
    public PanelCodigo() {
        initComponents();
        texto=new PanelTextos();
        texto.setBounds(0,0, 700, 300);
        this.add(texto);
        listaErroes=new ArrayList<NodoError>();
        errores= new PanelErrores(listaErroes);
        errores.setBounds(0,302,700,200);
        this.add(errores);
    }
    public void agregarErrores()
    {
       errores.errores=listaErroes;
       errores.mostrarErrores();
       listaErroes=new ArrayList<NodoError>();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
