package Analizador.CCSS;

import java_cup.runtime.Symbol;
import EstructurasDatos.NodoArbol;
import EstructurasDatos.NodoError;
import java.util.ArrayList;
//parser ccss

parser code
{:
    public String archivo="null";
    public static ArrayList<NodoError> sitactico= new ArrayList<NodoError>();
    public void agregarerror(int linea,int columna,String tipo,String men)
    {
       NodoError er= new NodoError(linea, columna, tipo, men,archivo);
       sitactico.add(er);
    }
    public static String errorSin="";
    public void syntax_error(Symbol s){
         agregarerror(s.left,s.right,"sintacitico",s.value.toString());
         errorSin=errorSin+"Error en la Línea " + (s.right+1) +" Columna "+s.left+ ". Identificador "+s.value + " no reconocido."+"\n";
         System.err.println("Error de Sintaxis---a");
         System.err.println(s.value.toString());
         System.err.println( "Linea " + s.left );
         System.err.println( "Columna " + s.right );
         
    }
    public  ArrayList<NodoError> Sin()
    {
        return sitactico;
    }
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
         agregarerror(s.left,s.right,"sintacitico",s.value.toString());   
         System.err.println("Error de Sintaxis----b");
         System.err.println(s.value.toString());
         System.err.println( "Linea " + s.left );
         System.err.println( "Columna " + s.right );
    }

:}
action code
{:
    // acciones que podemos hacer en le codigo
    NodoArbol raiz,izq,der,nodo;
    private NodoArbol CrearHoja(String produccion,String valor,int linea,int colum)
    {
        NodoArbol nodo= new NodoArbol(produccion,valor,linea,colum);
        return nodo;
    }
    private NodoArbol AddHijo(NodoArbol raiz,NodoArbol hijo){
            raiz.add(hijo);
            return raiz;
     }

:}

terminal String ALINEADO , IZQUIERDA , DERECHA , CENTRADO , JUSTIFICADO;

terminal String TEXTO;

terminal String FORMATO , NEGRILLA , CURSIVA , MAYUSC , MININ , CAPITALT;

terminal String LETRA , TAMTEX , FONDOELEMTO , AUTOREDIMEN ,VERTICAL,HORIZONTAL, VISIBLE ,     
BORDE , OPAQUE , COLORTEXT , GRUPO , ID;

terminal String CORCHEIZQ , CORCHEDER , PARIZQ , PARDER , PUNTOCOMA , DOSPUNTOS , IGUAL      
MAS , MENOS , POR , DIVI,COMA;

terminal String EVERDADERO , EFALSO , EID , ENUMERO , ECADENA;

nonterminal String inicio,cuerpo,bloqueccss;

nonterminal String  elemento,lelemento;

nonterminal String id ,grupo;

nonterminal String lpropiedades propiedad;

nonterminal String alineado, opalineado;

nonterminal String texto;

nonterminal String formato,lopfor, opfor;

nonterminal String letra,tamtex,fondoelemento;

nonterminal String autoredi , op1,op2;

nonterminal String visible,borde,opaque,colortext;

nonterminal String exp, val;

precedence left MAS,MENOS;
precedence left POR,DIVI;

start with inicio;

inicio ::= cuerpo;

cuerpo ::= cuerpo bloqueccss
	   | bloqueccss;

bloqueccss ::= EID CORCHEIZQ lelemento CORCHEDER;

lelemento ::= lelemento elemento
		  |elemento;

elemento ::=id lpropiedades
		 |grupo lpropiedades;

id  	::= ID PARIZQ EID PARDER PUNTOCOMA;

grupo   ::= GRUPO PARIZQ EID PARDER PUNTOCOMA;

lpropiedades ::= lpropiedades propiedad; 

propiedad	 ::= alineado
			 |texto
			 |formato
			 |letra
			 |tamtex
			 |fondoelemento
			 |autoredi
			 |visible
			 |borde
			 |opaque
			 |colortext;

alineado    ::= ALINEADO DOSPUNTOS IGUAL opalineado PUNTOCOMA;

opalineado  ::= JUSTIFICADO
			|CENTRADO
			|DERECHA
			|IZQUIERDA;

texto    ::= TEXTO DOSPUNTOS IGUAL exp PUNTOCOMA;

formato  ::= FORMATO DOSPUNTOS IGUAL lopfor PUNTOCOMA;

lopfor	::= lopfor COMA opfor
		|opfor;

opfor	::= NEGRILLA
		|CURSIVA
		|MAYUSC
		|MININ
		|CAPITALT;

letra   ::= LETRA DOSPUNTOS IGUAL ECADENA PUNTOCOMA;

tamtex  ::= TAMTEX DOSPUNTOS IGUAL exp PUNTOCOMA;

fondoelemento ::= FONDOELEMTO DOSPUNTOS IGUAL ECADENA PUNTOCOMA;

autoredi  ::= AUTOREDIMEN DOSPUNTOS IGUAL CORCHEIZQ op1 COMA op2 CORCHEDER PUNTOCOMA;

op1 ::= EVERDADERO
	|EFALSO;
 
op2 ::= VERTICAL
	|HORIZONTAL;

visible ::= VISIBLE DOSPUNTOS IGUAL op1 DOSPUNTOS;

borde   ::= BORDE DOSPUNTOS IGUAL CORCHEIZQ exp COMA ECADENA COMA op1 CORCHEDER PUNTOCOMA; 		

opaque  ::= OPAQUE DOSPUNTOS IGUAL op1;

colortext ::= COLORTEXT DOSPUNTOS IGUAL ECADENA;	

exp ::= exp MAS exp
	|exp MENOS exp
	|exp POR exp
	|exp DIVI exp
	|val;

val ::= ENUMERO
    |ECADENA;
