
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 21 14:49:14 CST 2018
//----------------------------------------------------

package Analizador.CCSS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAMTEX = 15;
  public static final int DOSPUNTOS = 31;
  public static final int POR = 35;
  public static final int NEGRILLA = 9;
  public static final int COLORTEXT = 23;
  public static final int JUSTIFICADO = 6;
  public static final int ENUMERO = 41;
  public static final int IZQUIERDA = 3;
  public static final int EVERDADERO = 38;
  public static final int PUNTOCOMA = 30;
  public static final int MININ = 12;
  public static final int HORIZONTAL = 19;
  public static final int IGUAL = 32;
  public static final int FORMATO = 8;
  public static final int LETRA = 14;
  public static final int ALINEADO = 2;
  public static final int EFALSO = 39;
  public static final int VERTICAL = 18;
  public static final int CORCHEIZQ = 26;
  public static final int CURSIVA = 10;
  public static final int GRUPO = 24;
  public static final int ID = 25;
  public static final int EID = 40;
  public static final int EOF = 0;
  public static final int PARIZQ = 28;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int MENOS = 34;
  public static final int DIVI = 36;
  public static final int FONDOELEMTO = 16;
  public static final int OPAQUE = 22;
  public static final int DERECHA = 4;
  public static final int ECADENA = 42;
  public static final int CENTRADO = 5;
  public static final int MAYUSC = 11;
  public static final int CORCHEDER = 27;
  public static final int TEXTO = 7;
  public static final int PARDER = 29;
  public static final int AUTOREDIMEN = 17;
  public static final int BORDE = 21;
  public static final int VISIBLE = 20;
  public static final int CAPITALT = 13;
  public static final int MAS = 33;
}

