/* The following code was generated by JFlex 1.6.1 */

package Analizador.CJS;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import EstructurasDatos.NodoError;
//Scanner para CHTML

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analizador/CJS/lexicoCJS.flex</tt>
 */
public class scannerCJS implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int ComentarioUnaLinea = 2;
  public static final int ComentarioMultiLinea = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\64\1\65\1\66\1\64\1\64\22\0\1\61\1\20\1\56"+
    "\2\0\1\15\1\23\1\25\1\4\1\5\1\14\1\11\1\3\1\12"+
    "\1\10\1\13\2\60\1\62\1\57\2\63\4\55\1\1\1\2\1\21"+
    "\1\17\1\22\2\0\1\33\1\50\1\44\1\36\1\31\1\32\2\51"+
    "\1\53\1\47\1\51\1\34\1\40\1\45\1\43\1\46\1\51\1\27"+
    "\1\52\1\26\1\30\1\41\1\51\1\42\2\51\3\0\1\16\1\54"+
    "\1\0\1\33\1\50\1\44\1\36\1\31\1\32\2\51\1\53\1\47"+
    "\1\51\1\34\1\40\1\45\1\43\1\46\1\51\1\27\1\52\1\26"+
    "\1\30\1\41\1\51\1\42\2\51\1\6\1\24\1\7\7\0\1\66"+
    "\252\0\2\37\115\0\1\35\u1ea8\0\1\66\1\66\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\1\1\20\1\21\1\22\2\1\1\23\4\24\1\1"+
    "\1\24\1\1\6\24\1\25\1\1\1\26\1\27\1\30"+
    "\1\31\1\32\1\1\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\3\0\3\24\1\0\1\44"+
    "\1\24\1\0\2\24\1\0\1\24\1\0\6\24\1\44"+
    "\1\24\5\0\3\24\3\0\2\24\1\0\2\24\1\0"+
    "\1\24\1\0\2\24\1\0\1\24\1\0\7\24\1\25"+
    "\1\45\3\0\3\24\2\0\1\46\2\24\1\47\1\24"+
    "\1\47\2\0\1\24\1\0\2\24\1\0\1\24\2\50"+
    "\1\24\1\51\2\24\1\46\1\24\3\0\1\24\1\0"+
    "\2\24\2\0\3\24\2\0\1\24\1\0\2\24\1\0"+
    "\5\24\1\52\2\0\1\24\1\0\1\24\1\53\2\0"+
    "\3\24\2\0\1\24\1\0\2\24\1\0\1\24\1\54"+
    "\3\24\1\55\1\0\1\24\2\56\2\0\1\57\1\60"+
    "\1\24\1\0\2\61\1\0\1\24\1\62\1\0\4\24"+
    "\1\0\1\63\2\0\1\24\1\64\2\65\1\0\3\24"+
    "\1\64\3\0\1\66\1\0\3\24\2\0\1\67\2\70"+
    "\1\24\1\67\1\0\2\71\1\72\11\0\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\245\0\245\0\245\0\245"+
    "\0\245\0\245\0\245\0\245\0\334\0\u0113\0\245\0\245"+
    "\0\245\0\245\0\u014a\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d"+
    "\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd"+
    "\0\245\0\245\0\u0604\0\245\0\u063b\0\u0672\0\245\0\245"+
    "\0\245\0\245\0\245\0\245\0\245\0\245\0\245\0\u06a9"+
    "\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0861"+
    "\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19"+
    "\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89"+
    "\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c\0\u0b9a\0\245\0\u1243"+
    "\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\245"+
    "\0\u13fb\0\u1432\0\245\0\u1469\0\u02cb\0\u14a0\0\u14d7\0\u150e"+
    "\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621\0\245\0\u02cb\0\u1658"+
    "\0\u02cb\0\u168f\0\u16c6\0\u02cb\0\u16fd\0\u1734\0\u176b\0\u17a2"+
    "\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5\0\u18ec\0\u1923\0\u195a"+
    "\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4\0\u1adb\0\u1b12"+
    "\0\u1b49\0\u1b80\0\u1bb7\0\u1bee\0\u1c25\0\245\0\u1c5c\0\u1c93"+
    "\0\u1cca\0\u1d01\0\u1d38\0\u02cb\0\u1d6f\0\u1da6\0\u1ddd\0\u1e14"+
    "\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95\0\u1fcc"+
    "\0\u2003\0\u02cb\0\u203a\0\u2071\0\u20a8\0\245\0\u20df\0\u2116"+
    "\0\245\0\u02cb\0\u214d\0\u2184\0\u02cb\0\u02cb\0\u21bb\0\u21f2"+
    "\0\245\0\u02cb\0\u2229\0\u2260\0\u02cb\0\u2297\0\u22ce\0\u2305"+
    "\0\u233c\0\u2373\0\u23aa\0\u02cb\0\u23e1\0\u2418\0\u244f\0\245"+
    "\0\245\0\u02cb\0\u2486\0\u24bd\0\u24f4\0\u252b\0\u02cb\0\u2562"+
    "\0\u2599\0\u25d0\0\u02cb\0\u2607\0\u263e\0\u2675\0\u26ac\0\u26e3"+
    "\0\u271a\0\245\0\245\0\u02cb\0\u2751\0\u02cb\0\u2788\0\245"+
    "\0\u02cb\0\245\0\u27bf\0\u27f6\0\u282d\0\u2864\0\u289b\0\u28d2"+
    "\0\u2909\0\u2940\0\u2977\0\245";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\2\32\1\34\1\35\1\32\1\36\1\37\1\40\1\41"+
    "\2\32\1\42\1\43\1\32\1\44\3\32\1\45\1\46"+
    "\1\4\1\47\1\50\2\47\1\51\2\47\1\51\1\52"+
    "\1\0\65\53\1\54\1\53\13\55\1\56\53\55\100\0"+
    "\1\57\67\0\1\60\73\0\1\61\66\0\1\62\66\0"+
    "\1\63\66\0\1\64\72\0\1\65\67\0\1\66\55\0"+
    "\1\67\12\0\1\70\3\0\1\71\24\0\2\72\1\0"+
    "\1\72\32\0\7\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\31\0\3\32\1\73\3\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\31\0"+
    "\2\32\1\74\4\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\31\0\1\75\6\32\1\0\1\32"+
    "\1\0\16\32\1\0\2\32\1\0\2\32\34\0\1\76"+
    "\5\0\1\77\13\0\1\77\41\0\3\32\1\100\3\32"+
    "\1\0\1\32\1\101\3\32\1\102\7\32\1\103\2\32"+
    "\1\0\2\32\1\0\2\32\43\0\1\104\54\0\3\32"+
    "\1\105\3\32\1\0\1\32\1\106\13\32\1\107\2\32"+
    "\1\0\2\32\1\0\2\32\31\0\7\32\1\0\1\32"+
    "\1\0\10\32\1\110\5\32\1\0\2\32\1\0\2\32"+
    "\31\0\5\32\1\111\1\32\1\0\1\32\1\0\3\32"+
    "\1\112\12\32\1\0\2\32\1\0\2\32\31\0\5\32"+
    "\1\113\1\32\1\0\1\32\1\0\16\32\1\0\2\32"+
    "\1\0\2\32\31\0\3\32\1\114\3\32\1\0\1\32"+
    "\1\77\13\32\1\115\2\32\1\0\2\32\1\0\2\32"+
    "\31\0\7\32\1\0\1\32\1\0\1\116\15\32\1\0"+
    "\2\32\1\0\2\32\13\0\1\117\44\0\1\47\1\0"+
    "\2\47\1\0\2\47\3\0\56\120\1\0\10\120\65\53"+
    "\1\0\1\53\13\55\1\0\53\55\25\0\1\54\70\0"+
    "\1\121\72\0\1\122\110\0\1\123\1\0\2\123\1\0"+
    "\2\123\31\0\1\124\6\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\7\32\1\0\1\32"+
    "\1\0\5\32\1\125\10\32\1\0\2\32\1\0\2\32"+
    "\31\0\3\32\1\126\3\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\127\5\0\1\130"+
    "\77\0\1\131\47\0\1\132\3\32\1\133\2\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\43\0"+
    "\1\134\54\0\7\32\1\0\1\32\1\0\4\32\1\135"+
    "\11\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\0\1\136\15\32\1\0\2\32\1\0\2\32"+
    "\51\0\1\137\46\0\7\32\1\0\1\32\1\0\5\32"+
    "\1\140\10\32\1\0\2\32\1\0\2\32\34\0\1\141"+
    "\63\0\3\32\1\142\3\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\143\6\32\1\144"+
    "\1\32\1\0\12\32\1\145\3\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\146\1\32\1\0\12\32\1\147"+
    "\3\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\0\5\32\1\150\10\32\1\0\2\32\1\0"+
    "\2\32\31\0\1\32\1\151\5\32\1\0\1\32\1\0"+
    "\16\32\1\0\2\32\1\0\2\32\31\0\1\152\5\32"+
    "\1\153\1\0\1\32\1\0\16\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\5\32\1\154"+
    "\10\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\0\6\32\1\155\7\32\1\0\2\32\1\0"+
    "\2\32\60\0\1\156\1\0\2\156\1\0\2\156\3\0"+
    "\56\120\1\157\10\120\30\0\1\160\72\0\1\161\45\0"+
    "\1\162\101\0\7\32\1\0\1\32\1\0\3\32\1\163"+
    "\12\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\0\4\32\1\164\11\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\2\32\1\165"+
    "\13\32\1\0\2\32\1\0\2\32\34\0\1\166\66\0"+
    "\1\167\100\0\1\170\51\0\3\32\1\171\3\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\31\0"+
    "\3\32\1\172\3\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\44\0\1\173\53\0\2\32\1\174"+
    "\4\32\1\0\1\32\1\0\16\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\1\32\1\175"+
    "\14\32\1\0\2\32\1\0\2\32\32\0\1\176\65\0"+
    "\7\32\1\177\1\32\1\0\12\32\1\200\3\32\1\0"+
    "\2\32\1\0\2\32\50\0\1\201\47\0\7\32\1\0"+
    "\1\32\1\0\5\32\1\202\10\32\1\0\2\32\1\0"+
    "\2\32\31\0\3\32\1\203\3\32\1\0\1\32\1\0"+
    "\16\32\1\0\2\32\1\0\2\32\34\0\1\204\63\0"+
    "\3\32\1\205\3\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\46\0\1\206\51\0\7\32\1\0"+
    "\1\32\1\0\3\32\1\207\12\32\1\0\2\32\1\0"+
    "\2\32\31\0\1\210\6\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\5\32\1\211\1\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\31\0\3\32\1\212\3\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\3\32\1\213\3\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\31\0\7\32\1\0\1\32\1\0\3\32\1\214\12\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\32\1\215\5\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\34\0\1\216\72\0\1\217\14\0\1\217\74\0\1\220"+
    "\34\0\1\32\1\221\5\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\7\32\1\0\1\32"+
    "\1\222\13\32\1\223\2\32\1\0\2\32\1\0\2\32"+
    "\31\0\1\224\6\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\37\0\1\225\76\0\1\226\50\0"+
    "\7\32\1\0\1\32\1\0\5\32\1\227\10\32\1\0"+
    "\2\32\1\0\2\32\31\0\7\32\1\0\1\32\1\0"+
    "\4\32\1\230\11\32\1\0\2\32\1\0\2\32\31\0"+
    "\7\32\1\0\1\32\1\0\1\231\15\32\1\0\2\32"+
    "\1\0\2\32\42\0\1\232\13\0\1\232\46\0\1\233"+
    "\61\0\5\32\1\234\1\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\235\66\0\1\236"+
    "\6\32\1\0\1\32\1\0\16\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\5\32\1\237"+
    "\10\32\1\0\2\32\1\0\2\32\32\0\1\240\65\0"+
    "\1\32\1\241\5\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\31\0\3\32\1\242\3\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\31\0"+
    "\6\32\1\243\1\0\1\32\1\0\16\32\1\0\2\32"+
    "\1\0\2\32\31\0\7\32\1\0\1\32\1\0\4\32"+
    "\1\244\11\32\1\0\2\32\1\0\2\32\31\0\7\32"+
    "\1\0\1\32\1\232\13\32\1\245\2\32\1\0\2\32"+
    "\1\0\2\32\30\0\1\246\72\0\1\247\112\0\1\250"+
    "\1\0\2\250\1\0\2\250\31\0\7\32\1\0\1\32"+
    "\1\0\5\32\1\251\10\32\1\0\2\32\1\0\2\32"+
    "\46\0\1\252\51\0\7\32\1\0\1\32\1\0\3\32"+
    "\1\253\12\32\1\0\2\32\1\0\2\32\31\0\7\32"+
    "\1\0\1\32\1\0\3\32\1\254\12\32\1\0\2\32"+
    "\1\0\2\32\34\0\1\255\101\0\1\256\50\0\3\32"+
    "\1\257\3\32\1\0\1\32\1\0\16\32\1\0\2\32"+
    "\1\0\2\32\31\0\1\260\6\32\1\0\1\32\1\0"+
    "\16\32\1\0\2\32\1\0\2\32\31\0\3\32\1\261"+
    "\3\32\1\0\1\32\1\0\16\32\1\0\2\32\1\0"+
    "\2\32\43\0\1\262\75\0\1\263\45\0\7\32\1\0"+
    "\1\32\1\0\7\32\1\264\6\32\1\0\2\32\1\0"+
    "\2\32\32\0\1\265\65\0\1\32\1\266\5\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\31\0"+
    "\3\32\1\267\3\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\44\0\1\270\53\0\7\32\1\0"+
    "\1\32\1\0\1\32\1\271\14\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\3\32\1\272"+
    "\12\32\1\0\2\32\1\0\2\32\31\0\3\32\1\273"+
    "\3\32\1\0\1\32\1\0\16\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\0\4\32\1\274"+
    "\11\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\0\1\275\15\32\1\0\2\32\1\0\2\32"+
    "\30\0\1\276\54\0\1\277\101\0\5\32\1\300\1\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\50\0\1\301\47\0\7\32\1\0\1\32\1\0\5\32"+
    "\1\302\10\32\1\0\2\32\1\0\2\32\43\0\1\303"+
    "\65\0\1\304\13\0\1\304\41\0\1\32\1\305\5\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\31\0\7\32\1\0\1\32\1\0\3\32\1\306\12\32"+
    "\1\0\2\32\1\0\2\32\31\0\7\32\1\0\1\32"+
    "\1\0\5\32\1\307\10\32\1\0\2\32\1\0\2\32"+
    "\42\0\1\310\13\0\1\310\44\0\1\311\63\0\3\32"+
    "\1\312\3\32\1\0\1\32\1\0\16\32\1\0\2\32"+
    "\1\0\2\32\36\0\1\313\61\0\5\32\1\314\1\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\31\0\1\32\1\315\5\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\36\0\1\316\61\0\5\32"+
    "\1\317\1\32\1\0\1\32\1\0\16\32\1\0\2\32"+
    "\1\0\2\32\31\0\7\32\1\0\1\32\1\0\1\320"+
    "\15\32\1\0\2\32\1\0\2\32\31\0\7\32\1\0"+
    "\1\32\1\304\13\32\1\321\2\32\1\0\2\32\1\0"+
    "\2\32\31\0\7\32\1\0\1\32\1\310\13\32\1\322"+
    "\2\32\1\0\2\32\1\0\2\32\60\0\1\323\1\0"+
    "\2\323\1\0\2\323\31\0\1\32\1\324\5\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\34\0"+
    "\1\325\100\0\1\326\51\0\1\327\6\32\1\0\1\32"+
    "\1\0\16\32\1\0\2\32\1\0\2\32\32\0\1\330"+
    "\74\0\1\331\14\0\1\331\42\0\7\32\1\331\1\32"+
    "\1\0\12\32\1\332\3\32\1\0\2\32\1\0\2\32"+
    "\41\0\1\333\56\0\7\32\1\0\1\334\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\3\32\1\335\3\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\31\0\7\32\1\0\1\32\1\0\3\32\1\336\12\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\32\1\337\5\32"+
    "\1\0\1\32\1\0\16\32\1\0\2\32\1\0\2\32"+
    "\60\0\1\340\1\0\2\340\1\0\2\340\50\0\1\341"+
    "\66\0\1\342\47\0\7\32\1\0\1\32\1\0\3\32"+
    "\1\343\12\32\1\0\2\32\1\0\2\32\46\0\1\344"+
    "\51\0\7\32\1\0\1\32\1\0\3\32\1\345\12\32"+
    "\1\0\2\32\1\0\2\32\31\0\7\32\1\0\1\32"+
    "\1\0\5\32\1\346\10\32\1\0\2\32\1\0\2\32"+
    "\31\0\7\32\1\0\1\32\1\0\5\32\1\347\10\32"+
    "\1\0\2\32\1\0\2\32\60\0\1\350\1\0\2\350"+
    "\1\0\2\350\31\0\1\351\73\0\1\352\62\0\1\353"+
    "\65\0\1\32\1\354\5\32\1\0\1\32\1\0\16\32"+
    "\1\0\2\32\1\0\2\32\31\0\1\355\6\32\1\0"+
    "\1\32\1\0\16\32\1\0\2\32\1\0\2\32\31\0"+
    "\5\32\1\356\1\32\1\0\1\32\1\0\16\32\1\0"+
    "\2\32\1\0\2\32\60\0\1\357\1\0\2\357\1\0"+
    "\2\357\46\0\1\360\51\0\7\32\1\0\1\32\1\0"+
    "\3\32\1\361\12\32\1\0\2\32\1\0\2\32\30\0"+
    "\1\362\33\0\1\363\65\0\1\364\1\0\1\364\61\0"+
    "\1\365\1\0\2\365\1\0\2\365\4\0\1\366\144\0"+
    "\2\367\1\0\2\367\60\0\1\370\1\0\2\370\1\0"+
    "\2\370\4\0\1\371\144\0\2\372\1\0\2\372\60\0"+
    "\1\373\1\0\2\373\1\0\2\373\30\0\1\374\41\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10670];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\11\11\2\1\4\11\26\1\2\11\1\1\1\11"+
    "\2\1\11\11\3\0\3\1\1\0\2\1\1\0\2\1"+
    "\1\0\1\1\1\0\10\1\5\0\3\1\3\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\1\0\10\1\1\11\3\0\3\1\2\0\1\11\2\1"+
    "\1\11\2\1\2\0\1\1\1\0\2\1\1\0\1\1"+
    "\1\11\7\1\3\0\1\1\1\0\2\1\2\0\3\1"+
    "\2\0\1\1\1\0\2\1\1\0\5\1\1\11\2\0"+
    "\1\1\1\0\2\1\2\0\3\1\2\0\1\1\1\0"+
    "\2\1\1\0\5\1\1\11\1\0\1\1\1\11\1\1"+
    "\2\0\3\1\1\0\1\11\1\1\1\0\2\1\1\0"+
    "\4\1\1\0\1\1\2\0\1\1\2\11\1\1\1\0"+
    "\4\1\3\0\1\1\1\0\3\1\2\0\2\11\3\1"+
    "\1\0\1\11\1\1\1\11\11\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Código de usuario
    public String archivo="null";
    public  ArrayList<NodoError> lexico= new ArrayList<NodoError>();
    public void agregarerror(int linea,int columna,String tipo,String men)
    {
       NodoError er= new NodoError(linea, columna, tipo, men,archivo);
       lexico.add(er);
    }
     public  ArrayList<NodoError> lex()
    {
        return lexico;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scannerCJS(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 228) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { agregarerror(yyline+1,yycolumn,"lexico","caracter irreconocible: "+yytext());
            }
          case 60: break;
          case 2: 
            { return new Symbol(sym.DOSPUNTOS, yyline, yycolumn, yytext());
            }
          case 61: break;
          case 3: 
            { return new Symbol(sym.PUNTOCOMA, yyline, yycolumn, yytext());
            }
          case 62: break;
          case 4: 
            { return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
          case 63: break;
          case 5: 
            { return new Symbol(sym.PARIZQ, yyline, yycolumn, yytext());
            }
          case 64: break;
          case 6: 
            { return new Symbol(sym.PARDER, yyline, yycolumn, yytext());
            }
          case 65: break;
          case 7: 
            { return new Symbol(sym.LLAVEIZQ, yyline, yycolumn, yytext());
            }
          case 66: break;
          case 8: 
            { return new Symbol(sym.LLAVEDER, yyline, yycolumn, yytext());
            }
          case 67: break;
          case 9: 
            { return new Symbol(sym.PUNTO, yyline, yycolumn, yytext());
            }
          case 68: break;
          case 10: 
            { return new Symbol(sym.MAS, yyline, yycolumn, yytext());
            }
          case 69: break;
          case 11: 
            { return new Symbol(sym.MENOS, yyline, yycolumn, yytext());
            }
          case 70: break;
          case 12: 
            { return new Symbol(sym.DIVI, yyline, yycolumn, yytext());
            }
          case 71: break;
          case 13: 
            { return new Symbol(sym.POR, yyline, yycolumn, yytext());
            }
          case 72: break;
          case 14: 
            { return new Symbol(sym.MOD, yyline, yycolumn, yytext());
            }
          case 73: break;
          case 15: 
            { return new Symbol(sym.POT, yyline, yycolumn, yytext());
            }
          case 74: break;
          case 16: 
            { return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          case 75: break;
          case 17: 
            { return new Symbol(sym.MENOR, yyline, yycolumn, yytext());
            }
          case 76: break;
          case 18: 
            { return new Symbol(sym.MAYOR, yyline, yycolumn, yytext());
            }
          case 77: break;
          case 19: 
            { yybegin(ComentarioUnaLinea);
            }
          case 78: break;
          case 20: 
            { return new Symbol(sym.EID, yyline, yycolumn, yytext());
            }
          case 79: break;
          case 21: 
            { return new Symbol(sym.ENUMERO, yyline, yycolumn, yytext());
            }
          case 80: break;
          case 22: 
            { /*Espacios en blanco, ignorados*/
            }
          case 81: break;
          case 23: 
            { /*Saltos de linea, ignorados*/
            }
          case 82: break;
          case 24: 
            { System.out.println("comentario 1"+yytext());
            }
          case 83: break;
          case 25: 
            { yybegin(YYINITIAL);
            }
          case 84: break;
          case 26: 
            { /**/System.out.println("comentario 2"+yytext());
            }
          case 85: break;
          case 27: 
            { return new Symbol(sym.AUMENTO, yyline, yycolumn, yytext());
            }
          case 86: break;
          case 28: 
            { return new Symbol(sym.DECREMENTO, yyline, yycolumn, yytext());
            }
          case 87: break;
          case 29: 
            { return new Symbol(sym.IGUALIGUAL, yyline, yycolumn, yytext());
            }
          case 88: break;
          case 30: 
            { return new Symbol(sym.DIFERENTE, yyline, yycolumn, yytext());
            }
          case 89: break;
          case 31: 
            { return new Symbol(sym.MENORIGUAL, yyline, yycolumn, yytext());
            }
          case 90: break;
          case 32: 
            { return new Symbol(sym.MAYOTIGUAL, yyline, yycolumn, yytext());
            }
          case 91: break;
          case 33: 
            { return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          case 92: break;
          case 34: 
            { return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          case 93: break;
          case 35: 
            { yybegin(ComentarioMultiLinea);
            }
          case 94: break;
          case 36: 
            { return new Symbol(sym.SI, yyline, yycolumn, yytext());
            }
          case 95: break;
          case 37: 
            { return new Symbol(sym.ECADENA, yyline, yycolumn, yytext());
            }
          case 96: break;
          case 38: 
            { return new Symbol(sym.SINO, yyline, yycolumn, yytext());
            }
          case 97: break;
          case 39: 
            { return new Symbol(sym.DIMV, yyline, yycolumn, yytext());
            }
          case 98: break;
          case 40: 
            { return new Symbol(sym.CASO, yyline, yycolumn, yytext());
            }
          case 99: break;
          case 41: 
            { return new Symbol(sym.PARA, yyline, yycolumn, yytext());
            }
          case 100: break;
          case 42: 
            { return new Symbol(sym.EVERDARERO, yyline, yycolumn, yytext());
            }
          case 101: break;
          case 43: 
            { return new Symbol(sym.ATEXTO, yyline, yycolumn, yytext());
            }
          case 102: break;
          case 44: 
            { return new Symbol(sym.CONTEO, yyline, yycolumn, yytext());
            }
          case 103: break;
          case 45: 
            { return new Symbol(sym.EFALSO, yyline, yycolumn, yytext());
            }
          case 104: break;
          case 46: 
            { return new Symbol(sym.FUNCION, yyline, yycolumn, yytext());
            }
          case 105: break;
          case 47: 
            { return new Symbol(sym.DETENER, yyline, yycolumn, yytext());
            }
          case 106: break;
          case 48: 
            { return new Symbol(sym.DEFECTO, yyline, yycolumn, yytext());
            }
          case 107: break;
          case 49: 
            { return new Symbol(sym.MENSAJE, yyline, yycolumn, yytext());
            }
          case 108: break;
          case 50: 
            { return new Symbol(sym.OBTENER, yyline, yycolumn, yytext());
            }
          case 109: break;
          case 51: 
            { return new Symbol(sym.RETORNAR, yyline, yycolumn, yytext());
            }
          case 110: break;
          case 52: 
            { return new Symbol(sym.IMPRIMIR, yyline, yycolumn, yytext());
            }
          case 111: break;
          case 53: 
            { return new Symbol(sym.MIENTRAS, yyline, yycolumn, yytext());
            }
          case 112: break;
          case 54: 
            { return new Symbol(sym.DOCUMETO, yyline, yycolumn, yytext());
            }
          case 113: break;
          case 55: 
            { return new Symbol(sym.SELECCIONA, yyline, yycolumn, yytext());
            }
          case 114: break;
          case 56: 
            { return new Symbol(sym.OBSERVADOR, yyline, yycolumn, yytext());
            }
          case 115: break;
          case 57: 
            { return new Symbol(sym.SETELEMENTO, yyline, yycolumn, yytext());
            }
          case 116: break;
          case 58: 
            { return new Symbol(sym.EDATE, yyline, yycolumn, yytext());
            }
          case 117: break;
          case 59: 
            { return new Symbol(sym.EDATETIME, yyline, yycolumn, yytext());
            }
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
