
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 24 01:05:25 CST 2018
//----------------------------------------------------

package Analizador.CJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AUMENTO = 27;
  public static final int DOSPUNTOS = 38;
  public static final int CASO = 8;
  public static final int POT = 26;
  public static final int POR = 24;
  public static final int MENSAJE = 16;
  public static final int IMPRIMIR = 13;
  public static final int SI = 5;
  public static final int OBSERVADOR = 18;
  public static final int FUNCION = 14;
  public static final int DIFERENTE = 30;
  public static final int OBTENER = 19;
  public static final int ENUMERO = 49;
  public static final int LLAVEDER = 44;
  public static final int DOCUMETO = 17;
  public static final int PUNTOCOMA = 39;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int MENORIGUAL = 33;
  public static final int SINO = 6;
  public static final int OR = 36;
  public static final int EDATE = 51;
  public static final int MIENTRAS = 11;
  public static final int EFALSO = 47;
  public static final int ATEXTO = 3;
  public static final int DIMV = 2;
  public static final int EID = 48;
  public static final int PARIZQ = 41;
  public static final int EOF = 0;
  public static final int MAYOTIGUAL = 34;
  public static final int SETELEMENTO = 20;
  public static final int EDATETIME = 52;
  public static final int DECREMENTO = 28;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int MENOS = 22;
  public static final int MENOR = 31;
  public static final int MOD = 25;
  public static final int DIVI = 23;
  public static final int MAYOR = 32;
  public static final int SELECCIONA = 7;
  public static final int DETENER = 12;
  public static final int PUNTO = 45;
  public static final int ECADENA = 50;
  public static final int IGUALIGUAL = 29;
  public static final int LLAVEIZQ = 43;
  public static final int PARA = 10;
  public static final int RETORNAR = 15;
  public static final int CONTEO = 4;
  public static final int PARDER = 42;
  public static final int DEFECTO = 9;
  public static final int EVERDARERO = 46;
  public static final int MAS = 21;
}

